### ISSUE TITLE
[iOS] pod install error

### ISSUE THREAD

**Issue by zzetao** [voids/weex-image-crop-picker#1]
![image](https://user-images.githubusercontent.com/8110936/33000290-17c5391e-cde2-11e7-9cdc-4c8ecf194358.png)

**Comment by voids** [comment]
Swift project?
Have you add "use_frameworks!" in your Podfile?
Please show your cocoapods version.

**Comment by zzetao** [comment]
Swift project?
> yes.

Have you add "use_frameworks!" in your Podfile?
> yes.

cocoapods version: 1.3.1

**Comment by voids** [comment]
Please execute "pod update" upgrade the module to 0.1.1, and try again.
