### ISSUE TITLE
图片怎么显示

### ISSUE THREAD

**Issue by zhuxiaozhuworking** [voids/weex-image-crop-picker#3]
想问问 iOS客户端上 ，发现照相机拍完照以后，图片并没有存储在图库中  而是在“react-native-image-crop-picker”的一个目录下存放   

这张照片怎么在img标签中显示 

怎么上传该图片，谢谢！

**Comment by voids** [comment]
#### 这个组件给你的图片是完整路径
- 跟显示本地图片一样，那是weex的image adapter的事，官方默认的实现是支持image标签src属性用"file://" 形式的。
- 上传图片建议用原生组件实现(比如我司直接用的七牛云存储所以直接封装了七牛的sdk)。如果想用官方的stream实现，stream源码中除了fetch还有个fetchWithArrayBuffer，看起来是接收base64字符串的。android就只有一个fetch.
```objective-C
WX_EXPORT_METHOD(@selector(fetchWithArrayBuffer:options:callback:progressCallback:))
```
- 以上问题跟本项目无关，你应该在weex项目中去提问。

**Comment by zhuxiaozhuworking** [comment]
嗯 你好  weex加载工程目录中的图片 我这边可以实现   但是这种全路径的怎么在weex中实现 ？ 我在weex项目下找了一天  还是没什么收获 您能指点我一下吗  谢谢您了

**Comment by voids** [comment]
我上面已经说了image标签是支持file scheme的，拿到的path没有scheme的话自己添加就可以了，比如ios下：

```html
<image class="test" :src="imagepath"/>
```

```javascript
let options = {
    width: 300,
    height: 300,
    mediaType: "photo",
    cropping: true
};
imageCropPicker.openPicker(options, response => {
    this.imagepath = "file://" + response.data.path;
});
```
