### ISSUE TITLE
Have anyone implemented this one into latest weex environment?

### ISSUE THREAD

**Issue by sushilparajuli** [voids/weex-image-crop-picker#4]

**Comment by voids** [comment]
Our app works well based weex 0.18.0.

**Comment by sushilparajuli** [comment]
Is there any chances to get support for latest weex (v1.2.9)  ?

**Comment by fumpierrez** [comment]
would like to see this working on newer weex versions 👍

**Comment by voids** [comment]
please have a look at weex sdk source code repo below
https://github.com/apache/incubator-weex
we can see the newest tag is 0.18.0
so I think "v1.2.9" that you mentioned maybe a js framework or weex toolkit.
